### ISSUE TITLE
All statements should include an id

### ISSUE THREAD

**Issue by thomasturrell** [xapijs/cmi5#101]
I do not believe that this library fulfils the following requirement from the cmi5 quartz specification:

> The AU MUST assign a statement id property in UUID format (as defined in the xAPI specification) for all statements it issues.

Forgive me if I have missed something. 

The code seems very clear and easy to follow.

**Comment by CookieCookson** [comment]
Hi @thomasturrell thanks for reporting an issue.

I've quite possibly misinterpreted this requirement as "IF a statement from the AU contains an ID, the ID must be in the UUID format", rather than "EVERY statement from the AU must have an ID, which is in the UUID format".

[Within the broader xAPI specification](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#241-id), the ID property is optional when creating statements from the AU and it suggests that the ID SHOULD be generated by the LRP, and MUST be created by the LRS if one is not supplied.

I'm happy to add an autogenerated ID from the client-side, although it does open up the rare possibility of an ID clash within the LRS. Do you think we would also need the option to manually specify/override the ID?

**Comment by thomasturrell** [comment]
In theory it's virtually impossible for a statement ID to clash with an existing one in the LRS. However in practice I have seen it happen (frequently), there are LRPs out in the wild which do not use at the correct algorithm for generating a UUID.

I am unsure why there is a requirement for the AU to generate the statement ID. Personally, I do not think the statement ID is useful to the AU, most implementations send and then forget statements.

In my opinion autogenerating the ID from the client side library (using a decent UUID library) without giving the option to override is the way to go.

**Comment by CookieCookson** [comment]
I cannot argue with that 😄  does #102 meet the criteria?

**Comment by thomasturrell** [comment]
> I cannot argue with that 😄 does #102 meet the criteria?

Looks good to me. I approved your pull request (which seems a bit weird, hopefully you don't mind!)

**Comment by CookieCookson** [comment]
Thanks @thomasturrell - the change will be included as part of the next release cycle.
